### ISSUE TITLE
Error while running vimeo-combine.sh script

### ISSUE THREAD

**Issue by misagarcia** [Tusko/vimeo-private-downloader#13]
Hi guys, Thanks so much for this awesome script. I tried it today and it didn't work for me. not sure if I'm doing something wrong, so apologize if this is something basic I'm missing.

I ran it using this `node vimeo-combine.sh`

Everything else ran perfectly fine, but when I got to combining the audio and video file, it returned this error. Has anyone else had this issue?

`SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47`

**Comment by misagarcia** [comment]
**UPDATED:** - I found the problem, I figured it out. I went and used `./` to run it instead of node. I'm new to this, so I'm learning as I go.
