### ISSUE TITLE
Expired links crashes the app

### ISSUE THREAD

**Issue by linomassarani** [Tusko/vimeo-private-downloader#16]
When there is a link in 'videojson.js' list that is expired the app crashes and finish.

What would you think could be a better solution? I was thinking that it could log a message to user set a new link, skip this one and try the next link.

```
undefined:1
410 Gone
    ^

SyntaxError: Unexpected token G in JSON at position 4
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> ([...]/vimeo-private-downloader/vimeomaster.js:130:41)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

```

**Comment by Tusko** [comment]
Fixed in the latest commit
