### ISSUE TITLE
SyntaxError: Unexpected token in JSON at position 0

### ISSUE THREAD

**Issue by yusufmsalh** [Tusko/vimeo-private-downloader#18]
I have 2 files ,one is completed and after running video master I have this error 

```
SyntaxError: Unexpected token G in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (E:\temp\vimeo-private-downloader-master\vimeo-private-downloader-master\vimeomaster.js:131:41)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```
hint : getJson function returns empty data.

**Comment by marcusademola** [comment]
I get similar error
SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/marx/downloads/stephanieQ/vimeomaster.js:5:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by Tusko** [comment]
Fixed in the latest commit
