### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by santoshthorani** [Tusko/vimeo-private-downloader#28]
I have followed all steps. Video and Audio is downloading but not working. it was working few months back not any more.
I tried on both Mac and Windows 10 but same result. Event combine script is not working.

**Comment by Tusko** [comment]
Can you provide some additional info, screenshots?

**Comment by siathalysedI** [comment]
It is not working for me too.

<img width="387" alt="Screen Shot 2021-05-06 at 0 10 18" src="https://user-images.githubusercontent.com/548549/117244885-7bc97c80-adff-11eb-8196-9601f3be63ec.png">
<img width="397" alt="Screen Shot 2021-05-06 at 0 10 22" src="https://user-images.githubusercontent.com/548549/117244892-7cfaa980-adff-11eb-8152-f42f48e42f55.png">

But no combined file as a result

**Comment by whysy** [comment]
Same error here, see logs in verbose mode

```
whysy@****:~/****/vimeo-private-downloader-master$ npm run combine --verbose
npm verb cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'combine', '--verbose' ]
npm info using npm@7.5.2
npm info using node@v12.21.0
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/usr/share/nodejs/npm/npmrc Completed in 1ms
npm timing config:load:builtin Completed in 1ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:/****/vimeo-private-downloader-master/.npmrc Completed in 1ms
npm timing config:load:project Completed in 1ms
npm timing config:load:file:/****/.npmrc Completed in 0ms
npm timing config:load:user Completed in 0ms
npm timing config:load:file:/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:cafile Completed in 0ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:setUserAgent Completed in 0ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 6ms
npm verb npm-session 6da5b5d5dce816b6
npm timing npm:load Completed in 14ms

> vimeodownload@1.0.0 combine
> sh vimeo-combine.sh

Runing Task 1 - Test.mp4
npm timing command:run-script Completed in 86ms
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (/usr/share/nodejs/@npmcli/promise-spawn/index.js:64:27)
npm verb stack     at ChildProcess.emit (events.js:314:20)
npm verb stack     at maybeClose (internal/child_process.js:1022:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
npm verb pkgid vimeodownload@1.0.0
npm verb cwd /****/vimeo-private-downloader-master
npm verb Linux 5.11.0-16-generic
npm verb argv "/usr/bin/node" "/usr/bin/npm" "run" "combine" "--verbose"
npm verb node v12.21.0
npm verb npm  v7.5.2
npm ERR! code 1
npm ERR! path /****/vimeo-private-downloader-master
npm ERR! command failed
npm ERR! command sh -c sh vimeo-combine.sh
npm verb exit 1
npm timing npm Completed in 199ms
```

If i try directly combine.sh, ffmpeg failed : 

```
ffmpeg version 4.3.2-0+deb11u1ubuntu1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10 (Ubuntu 10.2.1-20ubuntu1)
  configuration: --prefix=/usr --extra-version=0+deb11u1ubuntu1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x56535ab62480] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x56535ab62480] moov atom not found
parts/Test.m4a: Invalid data found when processing input
```


if it can help find the root cause.

**Comment by kervala** [comment]
I have the same problem.

Apparently Vimeo videos are now either crypted or some parts are missing because there is no moov atom anymore :( So the downloaded combined video is incomplete.

**Comment by pulak777** [comment]
### I think the script is working fine. But the issue is in the url.
`https://example.net/exp=1622963263~acl=%2Fc24741f9-d19d-47eb-be68-75ea9f942ec3%2F%2A~hmac=60ef747c6cec91a0d9206013ffc2b295e3feb953f347cb12c37fbc79ed089362/c24741f9-d19d-47eb-be68-75ea9f942ec3/sep/video/069278c5,8b45ebcd,f68e9946,281811e2/audio/4116dc67,70a93655/master.json?query_string_ranges=1&base64_init=1`
**(NOT work)** _will download **encrypted** `.m4v` and `.m4a` files_

`https://example.net/exp=1622963263~acl=%2Fc24741f9-d19d-47eb-be68-75ea9f942ec3%2F%2A~hmac=60ef747c6cec91a0d9206013ffc2b295e3feb953f347cb12c37fbc79ed089362/c24741f9-d19d-47eb-be68-75ea9f942ec3/sep/video/069278c5,8b45ebcd,f68e9946,281811e2/master.json?base64_init=1`
**(Work fine)** _will download **normal** `.m4v` and `.m4a` files_

So check the link before downloading.

**Comment by kervala** [comment]
Thank you so much @pulak777 :) Indeed it works better now, I didn't notice that :)
