### ISSUE TITLE
video is incomplete, restarting the download - ERROR

### ISSUE THREAD

**Issue by Unorthodoxis-ui** [Tusko/vimeo-private-downloader#46]
Error: found a segment with an empty url: {"start":0,"end":6.066666666666666,"url":"","size":1568577,"range":"8495-1577072"}
    at D:\Downloads\vimeo-private-downloader-master\index.js:88:13
    at Array.map (<anonymous>)
    at processFile (D:\Downloads\vimeo-private-downloader-master\index.js:86:32)
    at D:\Downloads\vimeo-private-downloader-master\index.js:40:5
    at IncomingMessage.<anonymous> (D:\Downloads\vimeo-private-downloader-master\index.js:154:29)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by Unorthodoxis-ui** [comment]
Had to include &query_string_ranges=1 to the URL. works fine now
